### ISSUE TITLE
TypeError: Cannot read property 'orgUrl' of undefined

### ISSUE THREAD

**Issue by cathalw92** [alexneo2003/playwright-azure-reporter#2]
Encountering the following error on initial setup. 

"TypeError: Cannot read property 'orgUrl' of undefined"

**azure.config.json**

```ts
{
    "token": "token",
    "orgUrl": "https://myURL.visualstudio.com/",
    "projectName": "MyProject",
    "testPlanId": 1555
}
```

**playwright.config.ts** 

```ts
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';
import azureConfig from './azure.config.json';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
const config: PlaywrightTestConfig = {
  testDir: './tests',
  /* Maximum time one test can run for. */
  timeout: 30 * 1000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 5000
  },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    ['list'],
    [
      '@alex_neo/playwright-azure-reporter',
      {
        token: azureConfig.token,
        orgUrl: azureConfig.orgUrl,
        projectName: azureConfig.projectName,
        planId:  azureConfig.testPlanId,
        environment: 'QA',
        testRunTitle: 'Playwright Test Run',
        uploadAttachments: true,
        isDisabled: false,
      }
    ]
  ],
```

**Comment by cathalw92** [comment]
> and if you write config directly at reporter config?
> 
> ```ts
> [
> '@alex_neo/playwright-azure-reporter',
>   {
>     token: 'token',
>     orgUrl: 'https://myURL.visualstudio.com/',
>     projectName: 'MyProject',
>     planId: 1555,
>   }
> ]
> ```



> and if you write config directly at reporter config?
> 
> ```ts
> [
> '@alex_neo/playwright-azure-reporter',
>   {
>     token: 'token',
>     orgUrl: 'https://myURL.visualstudio.com/',
>     projectName: 'MyProject',
>     planId: 1555,
>   }
> ]
> ```

Yes same error if I put it directly in playwright.config.ts. 

Full error 

TypeError: Cannot read property 'orgUrl' of undefined
    at new PlaywrightReporter (C:\test\node_modules\@alex_neo\playwright-azure-reporter\src\playwright-azure-reporter.ts:105:28)
    at Runner._createReporter (C:\test\node_modules\@playwright\test\lib\runner.js:150:24)
    at Runner.runAllTests (C:\test\node_modules\@playwright\test\lib\runner.js:178:22)
    at runTests (C:\test\node_modules\@playwright\test\lib\cli.js:162:18)
    at Ai.<anonymous> (C:\test\node_modules\@playwright\test\lib\cli.js:70:7)
