### ISSUE TITLE
Error when running tests

### ISSUE THREAD

**Issue by royalswe** [alexneo2003/playwright-azure-reporter#3]
I get this error after running `npx playwright test`
```
(node:16704) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of null
    at C:\Users\royal\source\repos\Playwright\node_modules\azure-devops-node-api\VsoClient.js:124:52
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
azure: Timeout while waiting for runId. Reporting is disabled.
```

part of my playwright.config.ts

```javascript
import type { PlaywrightTestConfig } from "@playwright/test";
import { devices } from "@playwright/test";
import { AzureReporterOptions } from './playwright-azure-reporter'

const config: PlaywrightTestConfig = {
  testDir: "./tests",
  /* Maximum time one test can run for. */
  timeout: 50 * 1000,
  expect: {
    timeout: 30000,
    toHaveScreenshot: {
      threshold: 0.2,
      maxDiffPixels: 150,
    }
  },
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  //reporter: 'html',
  reporter: [
    ['html'],
    [
      '@alex_neo/playwright-azure-reporter',
      {
        orgUrl: 'https://myCompany.visualstudio.com/myCompany',
        token: 'les5gavgkxobxgsjfsdfsfsdfsdfsayksv2pw2jvzsc3hxuqy5unadq',
        planId: 138086,
        projectName: "SampleSample",
        environment: 'myCompany',
        testRunTitle: 'Playwright Test Run',
        uploadAttachments: true,
        attachmentsType: ['screenshot', 'video', 'trace'],
      } as AzureReporterOptions
    ]
  ],
}
```
I copied the playwright-azure-reporter.ts from this repo directly to my root without any changes.
Did I miss any part in configuration?

**Comment by royalswe** [comment]
I entered wrong orgUrl
It should be `orgUrl: 'https://vssps.dev.azure.com/myCompany',` as the README explained
