### ISSUE TITLE
CI-CD run error:  TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by daniavander** [alexneo2003/playwright-azure-reporter#74]
when i want to run in azure devops pipeline, i get an error:

> ims@1.0.0 smoke
> playwright test --config=playwright.config.ts --project=chromesmoke --workers=1 --headed --grep @smoke

TypeError: Cannot read properties of undefined (reading 'replace')
    at AzureDevOpsReporter._anonymizeString (D:\a\1\s\node_modules\@alex_neo\playwright-azure-reporter\src\playwright-azure-reporter.ts:392:16)
    at AzureDevOpsReporter._anonymizeObject (D:\a\1\s\node_modules\@alex_neo\playwright-azure-reporter\src\playwright-azure-reporter.ts:403:28)
    at AzureDevOpsReporter._validateOptions (D:\a\1\s\node_modules\@alex_neo\playwright-azure-reporter\src\playwright-azure-reporter.ts:191:30)
    at new AzureDevOpsReporter (D:\a\1\s\node_modules\@alex_neo\playwright-azure-reporter\src\playwright-azure-reporter.ts:179:10)
    at createReporters (D:\a\1\s\node_modules\playwright\lib\runner\reporters.js:68:55)
    at Runner.runAllTests (D:\a\1\s\node_modules\playwright\lib\runner\runner.js:67:23)
    at runTests (D:\a\1\s\node_modules\playwright\lib\program.js:210:85)
    at t.<anonymous> (D:\a\1\s\node_modules\playwright\lib\program.js:54:7)
##[error]Cmd.exe exited with code '1'.
Finishing: RUN smoke tests

**Comment by daniavander** [comment]
it has worked last week, but i came from holiday, and get this error:S
i use at the same time these reporters (in the past i also used to: 
['list', { printSteps: true }],
    ['./my-awesome-reporter'],
    ['html', { open: 'never' }],
    ['junit', { outputFile: 'results.xml' }],
)

![image](https://github.com/user-attachments/assets/e13b2b83-fdeb-461a-bb43-ae8079b0c759)

**Comment by daniavander** [comment]
this occurs after the last merge: dd4a7a0c8d2646861aa571ba45dd91ab45703334
